services:
  server:
    build:
      context: ./server
      args:
        - ENVIRONMENT=dev
    ports:
      - "3000:3000"
    depends_on:
      - client

  client:
    build:
      context: ./client
      args:
        - ENVIRONMENT=dev
    ports:
      - "5000:80"